export const gradeCopy: Record<string, { oneLabel: string; one: string; twoLabel: string; two: string; optionOne: string; optionTwo: string }> = {
  "Macro fundamentals": { oneLabel: "Valid alignment", one: "A clear directional bias exists, supported by at least one meaningful macro factor, with no major unresolved contradiction.", twoLabel: "Strong alignment", two: "Multiple independent macro factors strongly support the same direction and reinforce the trade thesis.", optionOne: "Valid", optionTwo: "Strong" },
  "Higher-timeframe technical location": { oneLabel: "Valid location", one: "Price is at a legitimate higher-timeframe zone or structural area, but the location may be tested, less precise, or have limited confluence.", twoLabel: "High-quality location", two: "Price is at a fresh, clearly defined higher-timeframe zone with strong structural or profile confluence and clean room toward the target.", optionOne: "Valid", optionTwo: "Strong" },
  "Market archetype": { oneLabel: "Valid archetype", one: "The setup reasonably fits either a contrarian or momentum environment, although some supporting conditions are weaker or still developing.", twoLabel: "Clear archetype", two: "The market phase is unmistakably contrarian or momentum, and the key conditions strongly align with current price behaviour.", optionOne: "Valid", optionTwo: "Strong" },
  "Intraday structure": { oneLabel: "Actionable structure", one: "Intraday structure supports the trade, but the sequence is less clean, still developing, or contains minor ambiguity.", twoLabel: "Clean structure", two: "The market has clearly entered the execution phase with confirmed structure, directional control, and an obvious invalidation point.", optionOne: "Valid", optionTwo: "Strong" },
  "Entry-model quality": { oneLabel: "Valid entry model", one: "The complete entry model has formed and is technically valid, but the location, candle sequence, or timing is not textbook.", twoLabel: "Textbook entry model", two: "The entry model is fully complete at the planned level, with clean confirmation, precise timing, and no chased execution.", optionOne: "Valid", optionTwo: "Textbook" },
  "Risk and tradeability": { oneLabel: "Acceptable risk", one: "The stop is structurally valid and realistic 2R is available, but the entry, volatility, spread, or available space is less efficient.", twoLabel: "Optimal risk", two: "Invalidation is clear, entry is efficient, realistic 2R or more is available, and exposure, spread, news, and market conditions are fully acceptable.", optionOne: "Acceptable", optionTwo: "Optimal" }
};

export const gradeText = (title: string, score: 1 | 2, fallback: string) => { const copy = gradeCopy[title]; if (!copy) return fallback; return score === 1 ? `${copy.oneLabel} — ${copy.one}` : `${copy.twoLabel} — ${copy.two}`; };
