import { Shell } from "@/components/shell";
import { addEntryModel, addGateDefinition, addGradeCategory, updateEmotionalQuestion, updateEntryModel, updateGateDefinition, updateGradeCategory, updateStrategyConfiguration } from "@/app/actions";
import { prisma } from "@/lib/prisma";
import { guardPage } from "@/lib/supabase/page-guard";

export const dynamic = "force-dynamic";

export default async function EditStrategyPage() {
  const ownerId = await guardPage();
  const version = await prisma.strategyVersion.findFirst({ where: { ownerId }, include: { gates: { orderBy: { displayOrder: "asc" } }, emotionalQuestions: { orderBy: { displayOrder: "asc" } }, gradeCategories: { orderBy: { displayOrder: "asc" } }, entryModels: { orderBy: { code: "asc" } } }, orderBy: { versionNumber: "desc" } });
  if (!version) return <Shell><p className="notice">No strategy exists yet. Create one from Strategy Library.</p></Shell>;
  return <Shell>
    <p className="eyebrow">Strategy Builder · {version.status === "DRAFT" ? "Draft" : version.status} v{version.versionNumber}</p>
    <h1>Owner configuration</h1>
    <section className="card"><h2>Global operating rules</h2><form action={updateStrategyConfiguration}><input type="hidden" name="versionId" value={version.id}/><label className="field">Change summary<input name="changeSummary" defaultValue={version.changeSummary || ""}/></label><label className="field">Strategy configuration (editable owner data)<textarea name="configuration" defaultValue={JSON.stringify(JSON.parse(version.configuration), null, 2)}/></label><button>Save global rules</button></form></section>
    <section className="card"><h2>Mandatory gates</h2><form className="rule" action={addGateDefinition}><input type="hidden" name="strategyVersionId" value={version.id}/><div className="grid three"><label className="field">Gate ID<input required name="gateKey" placeholder="G01"/></label><label className="field">Question<input required name="title" placeholder="Owner-defined gate question"/></label><label className="field">Order<input required name="displayOrder" type="number" min="1"/></label></div><button>Add gate</button></form>{version.gates.map((gate) => <form className="rule" action={updateGateDefinition} key={gate.id}><input type="hidden" name="gateId" value={gate.id}/><label className="field">Question<input name="title" defaultValue={gate.title}/></label><div className="grid two"><label className="field">Explanation<textarea name="explanation" defaultValue={gate.explanation || ""}/></label><label className="field">Evidence / timeframe<textarea name="evidence" defaultValue={gate.evidence || ""}/><input name="timeframe" defaultValue={gate.timeframe || ""} placeholder="Relevant timeframe"/></label><label className="field">Yes criteria<textarea name="yesCriteria" defaultValue={gate.yesCriteria || ""}/></label><label className="field">No criteria<textarea name="noCriteria" defaultValue={gate.noCriteria || ""}/></label></div><label><input type="checkbox" name="active" value="true" defaultChecked={gate.active}/> Active</label> <button>Save gate {gate.displayOrder}</button></form>)}</section>
    <section className="card"><h2>Gate 15 emotional-readiness checklist</h2><p className="muted">Questions are versioned. Historical assessments retain their saved wording. The daily-limit and two-loss hard check is required in the initial version.</p>{version.emotionalQuestions.map((question) => <form className="rule" action={updateEmotionalQuestion} key={question.id}><input type="hidden" name="questionId" value={question.id}/><label className="field">Question wording<textarea name="wording" defaultValue={question.wording}/></label><div className="grid two"><label className="field">Order<input name="displayOrder" type="number" min="1" defaultValue={question.displayOrder}/></label><label className="field">Hard block<input type="checkbox" name="hardBlock" value="true" defaultChecked={question.hardBlock} disabled={question.questionId === "E08"}/></label></div><label><input type="checkbox" name="active" value="true" defaultChecked={question.active} disabled={question.questionId === "E08"}/> Active</label> <button>Save question {question.displayOrder}</button></form>)}</section>
    <section className="card"><h2>Grading categories</h2><form className="rule" action={addGradeCategory}><input type="hidden" name="strategyVersionId" value={version.id}/><div className="grid three"><label className="field">Category key<input required name="categoryKey" placeholder="MACRO"/></label><label className="field">Title<input required name="title" placeholder="Owner-defined category"/></label><label className="field">Order<input required name="displayOrder" type="number" min="1"/></label><label className="field">Score 1<textarea required name="scoreOne"/></label><label className="field">Score 2<textarea required name="scoreTwo"/></label></div><button>Add category</button></form>{version.gradeCategories.map((category) => <form className="rule" action={updateGradeCategory} key={category.id}><strong>{category.title}</strong><label className="field">Score 1<textarea name="scoreOne" defaultValue={category.scoreOne}/></label><label className="field">Score 2<textarea name="scoreTwo" defaultValue={category.scoreTwo}/></label><label className="field">Evidence / help<textarea name="evidence" defaultValue={category.evidence || ""}/><input name="helpText" defaultValue={category.helpText || ""}/></label><button>Save category</button></form>)}</section>
    <section className="card"><h2>Entry models</h2><form className="rule" action={addEntryModel}><input type="hidden" name="strategyVersionId" value={version.id}/><div className="grid three"><label className="field">Code<input required name="code" placeholder="EM1"/></label><label className="field">Name<input required name="name" placeholder="Owner-defined model"/></label><label className="field">Order<input required name="displayOrder" type="number" min="1"/></label></div><button>Add entry model</button></form>{version.entryModels.map((model) => <form className="rule" action={updateEntryModel} key={model.id}><input type="hidden" name="modelId" value={model.id}/><label className="field">Name<input name="name" defaultValue={model.name}/></label><label className="field">Short description<textarea name="shortDescription" defaultValue={model.shortDescription || ""}/></label><label><input type="checkbox" name="active" value="true" defaultChecked={model.active}/> Active</label> <button>Save model</button></form>)}</section>
  </Shell>;
}
