import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { dashboardFilters, dateRange } from "@/lib/dashboard-filters";

const cell = (value: string | number | null | undefined) => `"${String(value ?? "").replaceAll('"', '""')}"`;
export async function GET(request: NextRequest) {
  const filters = dashboardFilters(Object.fromEntries(request.nextUrl.searchParams.entries())); const range = dateRange(filters);
  if (!range.valid) return new Response("Custom start date must be before the end date.", { status: 400 });
  const trades = await prisma.trade.findMany({ where: { status: "CLOSED" }, include: { candidate: { include: { optionSelections: true, targets: true } }, strategyVersion: { include: { strategy: true } }, review: true }, orderBy: { createdAt: "desc" } });
  const visible = trades.filter((trade) => (!filters.account || trade.account === filters.account) && (!filters.version || trade.strategyVersionId === filters.version) && (!range.start || trade.createdAt >= range.start) && (!range.end || trade.createdAt < range.end) && (filters.source !== "verified" || trade.review?.status === "COMPLETE") && (filters.source !== "demo" || trade.candidate.thesis?.startsWith("DEMO:")));
  const labels = (trade: typeof visible[number], category: string) => trade.candidate.optionSelections.filter((selection) => selection.category === category).map((selection) => selection.labelSnapshot).join(" | ");
  const headings = ["Trade ID", "Date", "Symbol", "Entry timeframe", "Direction", "Strategy", "Strategy version", "Entry model", "Supply & Demand tags", "Macro Fundamental Bias tags", "Bias Evaluation", "Setup Type", "Entry Confluence", "Optional Confluences", "Entry Evaluation", "Target selections", "Custom target", "Close Status", "Trade Duration seconds", "Gross PnL", "Fees", "Net PnL", "Calculation method", "Setup grade", "Validity", "Outcome", "Executed R", "Planned-Capital R", "Maximum-Risk R", "Execution grade", "Management grade", "Primary mistake", "Post-Trade Review", "Lesson"];
  const rows = visible.map((trade) => [trade.id, trade.createdAt.toISOString(), trade.candidate.instrumentLabel || trade.instrument, trade.candidate.entryTimeframeCustom || trade.candidate.entryTimeframe, trade.direction, trade.strategyVersion.strategy.name, trade.strategyVersion.versionNumber, trade.entryModel, labels(trade, "SUPPLY_DEMAND"), labels(trade, "MACRO_BIAS"), trade.candidate.biasEvaluation, labels(trade, "SETUP_TYPE"), labels(trade, "ENTRY_CONFLUENCE"), labels(trade, "OPTIONAL_CONFLUENCE"), trade.candidate.entryEvaluation, trade.candidate.targets.map((target) => target.label).join(" | "), trade.candidate.targets.find((target) => target.price != null)?.price, trade.closeStatus, trade.durationSeconds, trade.grossPnl, trade.fees, trade.netResult, trade.pnlMethod, trade.gradeLetter, trade.review?.classification, trade.review?.outcome, trade.executedR, trade.plannedCapitalR, trade.maximumRiskR, trade.review?.executionGrade, trade.review?.managementGrade, trade.review?.primaryMistake, trade.review?.postTradeReview, trade.review?.lesson].map(cell).join(","));
  return new Response([headings.map(cell).join(","), ...rows].join("\n"), { headers: { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": "attachment; filename=evidence-ledger-journal.csv" } });
}
