import { PrismaClient, StrategyStatus } from "@prisma/client";
import { defaultStrategyConfiguration, EMOTIONAL_READINESS_QUESTIONS, ENTRY_MODEL_SHELLS, GATE_TITLES, GRADE_CATEGORIES } from "../src/lib/strategy-defaults";
import { JOURNAL_OPTION_LIBRARY } from "../src/lib/journal-options";
import { gradeForScores, rMeasurements } from "../src/lib/domain";
import { gradeText } from "../src/lib/grade-copy";

const prisma = new PrismaClient();
const historicGateTitles = [...GATE_TITLES.slice(0, 11), "Is at least 2R realistically available?", ...GATE_TITLES.slice(11)];

async function audit(entityType: string, entityId: string, action: string, metadata?: object) {
  await prisma.auditEvent.create({ data: { entityType, entityId, action, metadata: metadata ? JSON.stringify(metadata) : null } });
}

async function createVersionContent(versionId: string, gates: readonly string[], historical = false) {
  await prisma.gateDefinition.createMany({ data: gates.map((title, index) => ({ strategyVersionId: versionId, gateKey: historical || index < 11 ? `G${String(index + 1).padStart(2, "0")}` : `G${String(index + 2).padStart(2, "0")}`, title, explanation: "Owner configuration required", yesCriteria: "Owner configuration required", noCriteria: "Owner configuration required", evidence: "Owner configuration required", displayOrder: index + 1 })) });
  await prisma.emotionalQuestion.createMany({ data: EMOTIONAL_READINESS_QUESTIONS.map((wording, index) => ({ strategyVersionId: versionId, questionId: `E${String(index + 1).padStart(2, "0")}`, wording, displayOrder: index + 1, hardBlock: index === 7 })) });
  await prisma.gradeCategory.createMany({ data: GRADE_CATEGORIES.map((title, index) => ({ strategyVersionId: versionId, categoryKey: `GRADE_${index + 1}`, title, scoreOne: gradeText(title, 1, "Owner configuration required"), scoreTwo: gradeText(title, 2, "Owner configuration required"), displayOrder: index + 1 })) });
  await prisma.entryModel.createMany({ data: ENTRY_MODEL_SHELLS.map((code) => ({ strategyVersionId: versionId, code, name: code, shortDescription: code.startsWith("No EM") ? "No valid entry model — explanation required." : "Owner configuration required", fields: JSON.stringify({ requiredMacroContext: "Owner configuration required", candleSequence: "Owner configuration required", confirmationRule: "Owner configuration required", entryTrigger: "Owner configuration required", stopRule: "Owner configuration required" }) })) });
  await prisma.journalOption.createMany({ data: JOURNAL_OPTION_LIBRARY.map((option, index) => ({ strategyVersionId: versionId, ...option, displayOrder: index + 1 })) });
}

async function main() {
  await prisma.auditEvent.deleteMany(); await prisma.tradeReview.deleteMany(); await prisma.tradeLeg.deleteMany(); await prisma.trade.deleteMany(); await prisma.setupGrade.deleteMany(); await prisma.emotionalResponse.deleteMany(); await prisma.emotionalAssessment.deleteMany(); await prisma.gateResponse.deleteMany(); await prisma.gateAssessment.deleteMany(); await prisma.candidateOptionSelection.deleteMany(); await prisma.candidateTarget.deleteMany(); await prisma.setupCandidate.deleteMany(); await prisma.instrumentPlan.deleteMany(); await prisma.dailyPlan.deleteMany(); await prisma.instrumentMetadata.deleteMany(); await prisma.journalOption.deleteMany(); await prisma.entryModel.deleteMany(); await prisma.gradeCategory.deleteMany(); await prisma.gateDefinition.deleteMany(); await prisma.emotionalQuestion.deleteMany(); await prisma.strategyRule.deleteMany(); await prisma.strategyVersion.updateMany({ data: { parentVersionId: null } }); await prisma.strategyVersion.deleteMany(); await prisma.strategy.deleteMany();

  const strategy = await prisma.strategy.create({ data: { name: "LTA Evidence Ledger — Demo", description: "Clearly labelled demo strategy. Candle doctrine remains owner-configurable." } });
  const historic = await prisma.strategyVersion.create({ data: { strategyId: strategy.id, versionNumber: 1, status: StrategyStatus.PUBLISHED, effectiveDate: new Date("2026-07-01"), publishedAt: new Date("2026-07-01"), configuration: JSON.stringify({ ...defaultStrategyConfiguration, minimumRewardRisk: 2 }), changeSummary: "Historical demo version: 2R was mandatory" } });
  await createVersionContent(historic.id, historicGateTitles, true);
  const version = await prisma.strategyVersion.create({ data: { strategyId: strategy.id, versionNumber: 2, status: StrategyStatus.PUBLISHED, effectiveDate: new Date(), publishedAt: new Date(), parentVersionId: historic.id, configuration: JSON.stringify(defaultStrategyConfiguration), changeSummary: "2R moved from mandatory gate to optional execution confluence" } });
  await createVersionContent(version.id, GATE_TITLES);
  await audit("StrategyVersion", version.id, "STRATEGY_RULE_CHANGED_2R_OPTIONAL", { historicalVersionId: historic.id, mandatoryGates: 14 });

  await prisma.strategyRule.createMany({ data: [
    { strategyVersionId: version.id, ruleId: "risk-basis", title: "Account risk basis", description: "Owner configuration required: current balance, current equity, or start-of-day equity.", category: "Risk", mandatory: true, inputType: "SINGLE_SELECT", allowedAnswers: JSON.stringify(["Current balance", "Current equity", "Start-of-day equity"]), displayOrder: 1 },
    { strategyVersionId: version.id, ruleId: "optional-2r", title: "Realistic 2R", description: "Optional execution confluence. It can improve risk and tradeability scoring but cannot reject a setup.", category: "Execution", mandatory: false, inputType: "YES_NO", displayOrder: 2 }
  ] });
  await prisma.instrumentMetadata.createMany({ data: JOURNAL_OPTION_LIBRARY.filter((option) => option.category === "INSTRUMENT").map((option) => ({ strategyVersionId: version.id, symbol: option.label.replaceAll("/", ""), displayName: option.label, aliases: option.label === "XAU/USD" ? JSON.stringify(["XAUUSD"]) : null, assetClass: option.label.startsWith("6") || option.label === "MGC" ? "FUTURES" : option.label === "BTC/USD" ? "CRYPTO" : option.label.startsWith("X") ? "METAL" : "FOREX", tradingFormat: option.label.startsWith("6") || option.label === "MGC" ? "FUTURES" : "SPOT", quoteCurrency: option.label.includes("/") ? option.label.split("/")[1] : "USD", calculationSupported: false, metadataNotes: "Demo metadata intentionally incomplete — values are never guessed." })) });

  const plan = await prisma.dailyPlan.create({ data: { strategyVersionId: version.id, planDate: new Date(), account: "Demo Account", sessionLabels: JSON.stringify(["London"]), riskMode: "STANDARD", objective: "Demonstrate the expanded journal fields", maxTradeTheses: 2, readinessNotes: "Demo data — not real trading history", status: "ACTIVE", instruments: { create: { instrument: "XAUUSD", bias: "BULLISH", confidence: "High", archetype: "Momentum", macroNarrative: "Demo narrative only", profileLevels: "Demo previous-day VAL", permittedModels: JSON.stringify(["EM1"]), scenarios: JSON.stringify({ A: "Demo scenario" }) } } } });
  const options = await prisma.journalOption.findMany({ where: { strategyVersionId: version.id } });
  const selected = (labels: string[]) => labels.map((label, index) => { const option = options.find((item) => item.label === label)!; return { optionId: option.id, category: option.category, valueSnapshot: option.value, labelSnapshot: option.label, colourSnapshot: option.colour, displayOrder: index }; });
  const makeCandidate = async (values: { instrument: string; thesis: string; lifecycle?: "QUALIFIED" | "REJECTED"; grade?: number[]; trade?: boolean; invalid?: boolean; noEm?: boolean }) => {
    const candidate = await prisma.setupCandidate.create({ data: { strategyVersionId: version.id, dailyPlanId: plan.id, account: "Demo Account", instrument: values.instrument.replace("/", ""), instrumentLabel: values.instrument, sessionLabel: "London", direction: "LONG", archetype: "Momentum", entryModel: values.noEm ? "No EM — I just jumped in" : "EM1", entryTimeframe: "5m", entryTimeframeSeconds: 300, biasEvaluation: 8, entryEvaluation: values.noEm ? 1 : 8, noEntryModelExplanation: values.noEm ? "DEMO: impulsive entry, not an approved model." : null, thesis: values.thesis, plannedEntry: 100, plannedStop: 98, plannedTarget: 104, plannedRisk: 2, plannedPositionSize: 1, lifecycle: values.lifecycle ?? "QUALIFIED", optionSelections: { create: selected(["12H Demand Created", "SVI DIV LTF", "Bullish", "Macro Continuation", "Intra-day trend", "Realistic 2R available"]) }, targets: { create: [{ label: "PDH", primary: true, displayOrder: 0 }, { label: "3R", primary: false, displayOrder: 1 }] } } });
    const responses = GATE_TITLES.map((_, index) => ({ gateKey: index < 11 ? `G${String(index + 1).padStart(2, "0")}` : `G${String(index + 2).padStart(2, "0")}`, answer: values.lifecycle === "REJECTED" ? index !== 8 : true }));
    await prisma.gateAssessment.create({ data: { candidateId: candidate.id, result: values.lifecycle === "REJECTED" ? "REJECTED" : "PASSED", diagnosticCompletion: "COMPLETE", firstFailedGateKey: values.lifecycle === "REJECTED" ? "G09" : null, lockState: values.trade ? "LOCKED" : "DRAFT", responses: { create: responses }, emotionalAssessment: { create: { strategyVersionId: version.id, totalQuestions: EMOTIONAL_READINESS_QUESTIONS.length, answeredQuestions: EMOTIONAL_READINESS_QUESTIONS.length, passedQuestions: EMOTIONAL_READINESS_QUESTIONS.length, failedQuestions: 0, result: "PASSED", diagnosticCompletion: "COMPLETE", lockState: values.trade ? "LOCKED" : "DRAFT", responses: { create: EMOTIONAL_READINESS_QUESTIONS.map((questionTextSnapshot, index) => ({ questionId: `E${String(index + 1).padStart(2, "0")}`, questionTextSnapshot, answer: true })) } } } } });
    if (values.grade) { const graded = gradeForScores(values.grade); await prisma.setupGrade.create({ data: { candidateId: candidate.id, scores: JSON.stringify(values.grade), total: graded.total, letter: graded.letter, lockedAt: values.trade ? new Date() : null } }); }
    if (values.trade) { const r = rMeasurements({ netResult: values.invalid ? 150 : -100, executedRisk: 100, plannedCapitalRisk: 100, maximumRisk: 100 }); const trade = await prisma.trade.create({ data: { candidateId: candidate.id, strategyVersionId: version.id, account: "Demo Account", instrument: candidate.instrument, direction: "LONG", entryModel: candidate.entryModel, gradeLetter: values.grade ? gradeForScores(values.grade).letter : null, restrictionReason: values.invalid ? "Demo invalid win" : null, status: "CLOSED", entryPrice: 100, exitPrice: values.invalid ? 103 : 98, entryTimestamp: new Date("2026-08-02T04:00:00Z"), exitTimestamp: new Date("2026-08-02T05:32:00Z"), closeStatus: values.invalid ? "take_profit" : "stop_loss", durationSeconds: 5520, durationSource: "CALCULATED", targetPrice: 104, positionSize: 1, riskPercent: 2, riskAmount: 100, plannedR: 2, grossPnl: values.invalid ? 155 : -95, fees: 3, commission: 2, netResult: values.invalid ? 150 : -100, calculationCurrency: "USD", pnlMethod: "MANUAL", pnlPrecision: "MANUAL", executedRisk: 100, plannedCapitalRisk: 100, maximumRisk: 100, ...r, legs: { create: { entryPrice: 100, quantity: 1, stopPrice: 98, initialRisk: 100, reason: "Demo entry", planned: true } } } }); await prisma.tradeReview.create({ data: { tradeId: trade.id, status: "COMPLETE", takeAgain: !values.invalid, outcome: values.invalid ? "Win" : "Loss", classification: values.invalid ? "Invalid win" : "Valid loss", executionGrade: values.invalid ? "C" : "A", managementGrade: "B", answers: JSON.stringify({ demo: true }), primaryMistake: values.invalid ? "CHASE" : "NONE", postTradeReview: "Demo review paragraph one.\n\nDemo review paragraph two.", lesson: "Demo lesson — not real trading history", completedAt: new Date(), lastSavedAt: new Date() } }); }
    return candidate;
  };
  await makeCandidate({ instrument: "XAU/USD", thesis: "DEMO: Valid A+ Gold setup", grade: [2, 2, 2, 2, 2, 2] }); await makeCandidate({ instrument: "EUR/USD", thesis: "DEMO: Valid A setup", grade: [2, 2, 2, 1, 1, 1] }); await makeCandidate({ instrument: "GBP/USD", thesis: "DEMO: Confirmation-candle rejection", lifecycle: "REJECTED" }); await makeCandidate({ instrument: "USD/JPY", thesis: "DEMO: Chased-entry rejection", lifecycle: "REJECTED" }); await makeCandidate({ instrument: "AUD/USD", thesis: "DEMO: B-grade journal-only setup", grade: [2, 1, 1, 1, 1, 1] }); await makeCandidate({ instrument: "NZD/USD", thesis: "DEMO: Valid trade that loses", grade: [2, 2, 2, 1, 1, 1], trade: true }); await makeCandidate({ instrument: "USD/CHF", thesis: "DEMO: Invalid trade that wins", grade: [2, 1, 1, 1, 1, 1], trade: true, invalid: true, noEm: true });
  console.log(`Seeded demo strategy ${strategy.id}, current version ${version.id}, historical version ${historic.id}`);
}
main().finally(() => prisma.$disconnect());
