"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import type { DashboardTab, DateRangeKey, JournalSource } from "@/lib/dashboard-filters";
import styles from "./dashboard-controls.module.css";

type Option = { value: string; label: string };
const ranges: Option[] = [{ value: "today", label: "Today" }, { value: "week", label: "This week" }, { value: "last-week", label: "Last week" }, { value: "month", label: "This month" }, { value: "last-month", label: "Last month" }, { value: "30d", label: "Last 30 days" }, { value: "90d", label: "Last 90 days" }, { value: "year", label: "This year" }, { value: "all", label: "All time" }, { value: "custom", label: "Custom range" }];
export function DashboardControls({ tab, source, account, strategy, version, instrument, setupType, entryModel, grade, validity, direction, session, closeStatus, mistake, range, start, end, group, accounts, strategies, versions, instruments, setupTypes, entryModels, mistakes }: { tab: DashboardTab; source: JournalSource; account?: string; strategy?: string; version?: string; instrument?: string; setupType?: string; entryModel?: string; grade?: string; validity?: string; direction?: string; session?: string; closeStatus?: string; mistake?: string; range: DateRangeKey; start?: string; end?: string; group?: string; accounts: Option[]; strategies: Option[]; versions: Option[]; instruments: Option[]; setupTypes: Option[]; entryModels: Option[]; mistakes: Option[] }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams(); const [status, setStatus] = useState("");
  const set = (key: string, value?: string) => { const next = new URLSearchParams(search.toString()); if (value) next.set(key, value); else next.delete(key); router.push(`${pathname}?${next.toString()}`); };
  const exportCsv = async () => { setStatus("Preparing CSV export…"); try { const response = await fetch(`/api/journal-export?${search.toString()}`); if (!response.ok) throw new Error(); const blob = await response.blob(); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = "evidence-ledger-journal.csv"; link.click(); URL.revokeObjectURL(href); setStatus("CSV exported."); } catch { setStatus("Export could not be completed."); } };
  const select = (label: string, key: string, value: string | undefined, options: Option[], all = "All") => <label><span>{label}</span><select aria-label={label} value={value ?? ""} onChange={(event) => set(key, event.target.value || undefined)}><option value="">{all}</option>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>;
  return <><div className={styles.toolbar}><div className={styles.filters}><div className={styles.tabs} role="tablist" aria-label="Dashboard views">{(["journal", "comparison", "analysis"] as DashboardTab[]).map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} className={tab === item ? styles.selected : ""} onClick={() => set("tab", item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>{select("Journal", "source", source, [{ value: "verified", label: "Verified" }, { value: "demo", label: "Demo" }], "All journals")}{select("Account", "account", account, accounts)}{select("Strategy", "strategy", strategy, strategies)}{select("Version", "version", version, versions)}{select("Instrument", "instrument", instrument, instruments)}{select("Setup type", "setupType", setupType, setupTypes)}{select("Entry model", "entryModel", entryModel, entryModels)}{select("Grade", "grade", grade, ["A_PLUS", "A", "B", "C", "REJECTED"].map((value) => ({ value, label: value.replace("_PLUS", "+") })))}{select("Validity", "validity", validity === "all" ? "" : validity, [{ value: "valid", label: "Valid" }, { value: "invalid", label: "Invalid" }])}{select("Direction", "direction", direction === "all" ? "" : direction, [{ value: "LONG", label: "Long" }, { value: "SHORT", label: "Short" }])}{select("Session", "session", session, ["Asia", "London", "New York AM"].map((value) => ({ value, label: value })))}{select("Close status", "closeStatus", closeStatus, ["take_profit", "stop_loss", "breakeven"].map((value) => ({ value, label: value.replace("_", " ") })))}{select("Mistake", "mistake", mistake, mistakes)}<label><span>Date</span><select aria-label="Date range" value={range} onChange={(event) => set("range", event.target.value)}>{ranges.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{range === "custom" && <><input aria-label="Custom start date" type="date" value={start ?? ""} onChange={(event) => set("start", event.target.value)} /><input aria-label="Custom end date" type="date" value={end ?? ""} onChange={(event) => set("end", event.target.value)} /></>}<label><span>Group</span><select aria-label="Group by" value={group ?? "week"} onChange={(event) => set("group", event.target.value)}>{["day", "week", "month", "year"].map((value) => <option key={value} value={value}>{`By ${value}`}</option>)}</select></label></div><div className={styles.actions}><button type="button" onClick={() => router.push(`${pathname}?tab=${tab}`)}>Reset filters</button><button type="button" onClick={exportCsv}>Export</button><Link href="/journal/new">Manual entry</Link><span title="Broker synchronization is not available in the current version." aria-label="Broker synchronization unavailable">No broker sync</span><Link className="new" href="/journal/new">+ New Setup</Link></div></div><p className={styles.feedback} aria-live="polite">{status}</p></>;
}
