import { Shell } from "@/components/shell";
import { saveDailyPlan } from "@/app/actions";
import { prisma } from "@/lib/prisma";
import { reducedRiskReasons, SESSION_LABELS } from "@/lib/strategy-defaults";

export const dynamic = "force-dynamic";

export default async function PlanPage() {
  const [strategy, plans] = await Promise.all([prisma.strategyVersion.findFirst({ where: { status: "PUBLISHED" }, orderBy: { versionNumber: "desc" } }), prisma.dailyPlan.findMany({ orderBy: { planDate: "desc" }, take: 12, include: { strategyVersion: true, instruments: true } })]);
  return <Shell><div className="title-row"><div><p className="eyebrow">Plan</p><h1>Daily Plan</h1><p className="muted">Macro doctrine is owner-entered context in Phase 1; the app does not calculate a bias.</p></div></div>{strategy && <section className="card"><h2>Create plan</h2><form action={saveDailyPlan}><input type="hidden" name="strategyVersionId" value={strategy.id}/><div className="grid three"><label className="field">Date<input required type="date" name="planDate" defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="field">Account<input required name="account" defaultValue="Primary account"/></label><label className="field">Session label<select name="sessionLabel">{SESSION_LABELS.map((s) => <option key={s}>{s}</option>)}</select></label><label className="field">Risk mode<select name="riskMode"><option value="STANDARD">Standard · 2%</option><option value="REDUCED">Reduced · 1%</option></select></label><label className="field">Reduced-risk reason<select name="reducedRiskReason"><option value="">Not applicable</option>{reducedRiskReasons.map((r) => <option key={r}>{r}</option>)}</select></label><label className="field">Daily objective<input name="objective" placeholder="Process objective"/></label></div><label className="field">Personal readiness notes<textarea name="readinessNotes" placeholder="Energy, focus, emotional state"/></label><p className="muted">Session is a manual analytics classification. No time-window or DST rule is applied. Account risk basis remains configured by the strategy owner.</p><button>Activate daily plan</button></form></section>}<section className="card"><h2>Recent plans</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Account</th><th>Version</th><th>Session</th><th>Risk mode</th><th>Objective</th></tr></thead><tbody>{plans.map((plan) => <tr key={plan.id}><td>{plan.planDate.toLocaleDateString()}</td><td>{plan.account}</td><td>v{plan.strategyVersion.versionNumber}</td><td>{plan.sessionLabels}</td><td>{plan.riskMode}</td><td>{plan.objective}</td></tr>)}</tbody></table></div></section></Shell>;
}
